package com.asset.controller.test;

// Failed to get sources. Instead, stub sources have been generated by the disassembler.
// Implementation of methods is unavailable.
public abstract interface ModelDataJsonConstants {

    public static final java.lang.String MODEL_ID = "modelId";

    public static final java.lang.String MODEL_NAME = "name";

    public static final java.lang.String MODEL_REVISION = "revision";

    public static final java.lang.String MODEL_DESCRIPTION = "description";
}
