# From java:8-jre
From hub.c.163.com/library/java:8-jre

COPY abpm-process-center/simsun.ttc /usr/share/fonts/simsun.ttc
ADD abpm-process-center/target/1911011045-abpm-process-center-1.0-SNAPSHOT.jar app.jar

EXPOSE 9000

ENTRYPOINT ["java", "-jar", "app.jar"]

